// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrigamiBack.Data;

#nullable disable

namespace OrigamiBack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427202321_AddProductosTables")]
    partial class AddProductosTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrigamiBack.Data.Modelos.Categorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("categorias", "public");
                });

            modelBuilder.Entity("OrigamiBack.Data.Modelos.Celular", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("marca")
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.HasKey("id");

                    b.ToTable("celulares", "public");
                });

            modelBuilder.Entity("OrigamiBack.Data.Modelos.CondicionProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("condiciones_producto", "public");
                });

            modelBuilder.Entity("OrigamiBack.Data.Modelos.Marcas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("marcas", "public");
                });

            modelBuilder.Entity("OrigamiBack.Data.Modelos.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<byte[]>("Img")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("img");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.HasKey("Id");

                    b.ToTable("productos", "public");
                });

            modelBuilder.Entity("OrigamiBack.Data.Modelos.ProductosVariantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Almacenamiento")
                        .HasColumnType("text")
                        .HasColumnName("almacenamiento");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<int?>("CondicionId")
                        .HasColumnType("integer")
                        .HasColumnName("condicion_id");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("bytea")
                        .HasColumnName("imagen");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric")
                        .HasColumnName("precio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductoId");

                    b.Property<string>("Ram")
                        .HasColumnType("text")
                        .HasColumnName("ram");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.HasIndex("CondicionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("productos_variantes", "public");
                });

            modelBuilder.Entity("OrigamiBack.Data.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("usuarios", "public");
                });

            modelBuilder.Entity("OrigamiBack.Data.Vistas.VProductosConVariantes", b =>
                {
                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Almacenamiento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("almacenamiento");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<int>("Condicion")
                        .HasColumnType("integer")
                        .HasColumnName("condicion");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<int>("PrecioModelo")
                        .HasColumnType("integer")
                        .HasColumnName("preciomodelo");

                    b.ToTable((string)null);

                    b.ToView("VProductosConVariantes", "public");
                });

            modelBuilder.Entity("OrigamiBack.Data.Modelos.ProductosVariantes", b =>
                {
                    b.HasOne("OrigamiBack.Data.Modelos.CondicionProducto", "Condicion")
                        .WithMany("Variantes")
                        .HasForeignKey("CondicionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OrigamiBack.Data.Modelos.Productos", "Producto")
                        .WithMany("Variantes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condicion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("OrigamiBack.Data.Modelos.CondicionProducto", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("OrigamiBack.Data.Modelos.Productos", b =>
                {
                    b.Navigation("Variantes");
                });
#pragma warning restore 612, 618
        }
    }
}
